### ISSUE TITLE
missing Authorization header should fail immediately if required 

### ISSUE THREAD

**Issue by yoeluk** [team-carepay/traefik-jwt-plugin#43]
I am testing this plugin for validating jwt with treaffik but it looks like opa is needed even if I only want to validate the jwt.

```
  apiVersion: traefik.containo.us/v1alpha1
  kind: Middleware
  metadata:
    name: jwt
  spec:
    plugin:
      jwt:
        Required: true
        Keys:
          - https://authz.authentication.svc:8080/keys
```
if I don't set the OpaUrl the request is always authorized regardless of whether the `Authorization` header is set. If I set the OpaUrl, opa is called regardless of the `Authorization` header. 

I am using v0.0.11
