### ISSUE TITLE
How to use simple symetric key

### ISSUE THREAD

**Issue by hpsjakob** [team-carepay/traefik-jwt-plugin#45]
Hi,

I'm trying to use this plugin with a simple symmetric key. For example: `Eekee9saaBus7shoh1hau6lahYo9ah`.
I tried to specify it in the config like this:

```yml
jwt:
  Keys:
    - Eekee9saaBus7shoh1hau6lahYo9ah
  Alg: HS254
```

But I get the following error:

```
Invalid configuration, expecting a certificate, public key or JWK URL 
```

The readme stats:
> Allowed values include certificates, public keys, symmetric keys.

However, I did not get how to specify my symmetric key here.
Could you give me a hint how to achieve this? 

Thank you for your time in advance!
